#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Tsuji <s23c1093hj@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 1
for line in sys.stdin:
    line = line.rstrip()
    ans *= int(line)

print(ans)
