#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Tsuji <s23c1093hj@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

n = int(sys.stdin.read().strip())
print(n, end="=")
i = 2

while (i < n):
    if (n%i == 0):
        print(i, end="*")
        n //= i
    else:
        i += 1

print(n)
